# Generated by Django 4.2.20 on 2025-03-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_gene_symbol', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('concept_id', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'disease_capture_ncbi_df',
            },
        ),
    ]
