# Generated by Django 4.2.20 on 2025-03-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytable',
            name='id',
        ),
        migrations.AlterField(
            model_name='mytable',
            name='primary_gene_symbol',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
