# Generated by Django 4.2.20 on 2025-03-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_remove_mytable_id_alter_mytable_primary_gene_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
