# Generated by Django 4.2.20 on 2025-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_mytable_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='concept_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='relationship',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
